name: Build and test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: swift test -v --enable-code-coverage
    - name: Test coverage
      uses: maxep/spm-lcov-action@0.3.0
      with:
        output-file: ./coverage/lcov.info
    - name: Codecov
      uses: codecov/codecov-action@v2.0.1
